stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the project"
  only:
    - main

test-job:
  stage: test
  script:
    - echo "Running tests"
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - echo "Deploying the project"
  only:
    - main